name: 'Pleasant Commenter'
description: 'Posts a comment to a PR / issues, if re-triggered the old comment will be deleted and a new one added.'
inputs:
  id:
    description: 'Used to identify old comments to delete'
    required: true
  body:
    description: 'Comment to be added to the issue / PR'
    required: true
  github-token:
    description: 'Access token used to add / delete comments'
    required: true
  issue:
    description: 'Issue / PR the comment should be added to. Defaults to current Issue / PR.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
