name: 'Comment on Issue/PR'
description: 'Posts a comment to a PR / issues. Properly, handles previously made comments.'
inputs:
  id:
    description: 'Used to identify previously made comments'
    required: true
  body:
    description: 'Comment to be added to the issue / PR'
    required: false
  bodyFilepath:
    description: 'Path to a file containing comment to be added to the issue / PR'
    required: false
  github-token:
    description: 'Access token used to add / delete comments'
    required: true
  mode:
    description: >
      Specifies what happens to previously made comments.
      One of "delete-previous", "update-previous", "keep-previous".
    required: false
    default: "delete-previous"
  issue:
    description: 'Issue / PR the comment should be added to. Defaults to current Issue / PR.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
