on:
- pull_request

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: RasaHQ/create-comment@master
      with:
        id: 'test-comment'
        mode: 'update-previous'
        body: 'Hello world! Run ID: ${{github.run_id}}'
        github-token: ${{secrets.GITHUB_TOKEN}}
